{
    "swagger": "2.0",
    "info": {
        "title": "MiW16 Results REST api",
        "description": "[UPM] MiW16 Results REST api operations",
        "license": {
            "name": "MIT",
            "url": "./LICENSE.txt"
        },
        "version": "0.1.0"
    },
    "host": "localhost:8000",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/results": {
            "get": {
                "tags": [
                    "Results"
                ],
                "summary": "Returns all results",
                "description": "Returns all results from the system that the result has access to.",
                "operationId": "miw_cget_results",
                "responses": {
                    "200": {
                        "description": "Results array response",
                        "schema": {
                            "$ref": "#/definitions/ResultsArray"
                        }
                    },
                    "404": {
                        "description": "Results object not found",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Results"
                ],
                "summary": "Creates a new result",
                "description": "Creates a new result",
                "operationId": "miw_post_results",
                "parameters": [
                    {
                        "name": "data",
                        "in": "body",
                        "description": "`Results` properties to add to the system",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResultData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "`Created` Results created",
                        "schema": {
                            "$ref": "#/definitions/Results"
                        }
                    },
                    "400": {
                        "description": "`Bad Request` Resultsname or email already exists.",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    },
                    "422": {
                        "description": "`Unprocessable entity` Resultsname, e-mail or password is left out",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            },
            "options": {
                "tags": [
                    "Results"
                ],
                "summary": "Provides the list of HTTP supported methods",
                "description": "Return a `Allow` header with a list of HTTP supported methods.",
                "operationId": "miw_options_results",
                "responses": {
                    "200": {
                        "description": "`Allow` header &lt;Response body is empty&gt;"
                    }
                }
            }
        },
        "/results/{resultId}": {
            "get": {
                "tags": [
                    "Results"
                ],
                "summary": "Returns a result based on a single ID",
                "description": "Returns the result identified by `resultId`.",
                "operationId": "miw_get_results",
                "parameters": [
                    {
                        "$ref": "#/parameters/resultId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Results",
                        "schema": {
                            "$ref": "#/definitions/Results"
                        }
                    },
                    "404": {
                        "description": "Results id. not found",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Results"
                ],
                "summary": "Updates a result",
                "description": "Updates the result identified by `resultId`.",
                "operationId": "miw_put_results",
                "parameters": [
                    {
                        "$ref": "#/parameters/resultId"
                    },
                    {
                        "name": "data",
                        "in": "body",
                        "description": "`Results` data to update",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResultData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "`Ok` Results previously existed and is now updated",
                        "schema": {
                            "$ref": "#/definitions/Results"
                        }
                    },
                    "400": {
                        "description": "`Bad Request` Results name or e-mail already exists",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    },
                    "404": {
                        "description": "`Not Found` The result could not be found",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Results"
                ],
                "summary": "Deletes a result",
                "description": "Deletes the result identified `resultId`.",
                "operationId": "miw_delete_results",
                "parameters": [
                    {
                        "$ref": "#/parameters/resultId"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Results deleted &lt;Response body is empty&gt;"
                    },
                    "404": {
                        "description": "Results not found",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns all users",
                "description": "Returns all users from the system that the user has access to.",
                "operationId": "miw_cget_users",
                "responses": {
                    "200": {
                        "description": "User array response",
                        "schema": {
                            "$ref": "#/definitions/UsersArray"
                        }
                    },
                    "404": {
                        "description": "User object not found",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Creates a new user",
                "description": "Creates a new user",
                "operationId": "miw_post_users",
                "parameters": [
                    {
                        "name": "data",
                        "in": "body",
                        "description": "`User` properties to add to the system",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "`Created` User created",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "`Bad Request` Username or email already exists.",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    },
                    "422": {
                        "description": "`Unprocessable entity` Username, e-mail or password is left out",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            },
            "options": {
                "tags": [
                    "Users"
                ],
                "summary": "Provides the list of HTTP supported methods",
                "description": "Return a `Allow` header with a list of HTTP supported methods.",
                "operationId": "miw_options_users",
                "responses": {
                    "200": {
                        "description": "`Allow` header &lt;Response body is empty&gt;"
                    }
                }
            }
        },
        "/users/{userId}": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns a user based on a single ID",
                "description": "Returns the user identified by `userId`.",
                "operationId": "miw_get_users",
                "parameters": [
                    {
                        "$ref": "#/parameters/userId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "404": {
                        "description": "User id. not found",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Users"
                ],
                "summary": "Updates a user",
                "description": "Updates the user identified by `userId`.",
                "operationId": "miw_put_users",
                "parameters": [
                    {
                        "$ref": "#/parameters/userId"
                    },
                    {
                        "name": "data",
                        "in": "body",
                        "description": "`User` data to update",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "`Ok` User previously existed and is now updated",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "`Bad Request` User name or e-mail already exists",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    },
                    "404": {
                        "description": "`Not Found` The user could not be found",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Users"
                ],
                "summary": "Deletes a user",
                "description": "Deletes the user identified `userId`.",
                "operationId": "miw_delete_users",
                "parameters": [
                    {
                        "$ref": "#/parameters/userId"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "User deleted &lt;Response body is empty&gt;"
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/Message"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Result": {
            "required": [
                "id",
                "result"
            ],
            "properties": {
                "id": {
                    "description": "Result Id",
                    "type": "integer",
                    "format": "int32"
                },
                "result": {
                    "description": "Result result",
                    "type": "int32"
                },
                "user_id": {
                    "description": "Result user associated",
                    "type": "int32"
                },
                "time": {
                    "description": "Result time",
                    "type": "datetime"
                }
            },
            "example": {
                "id": 1508,
                "result": 100,
                "user_id": 1,
                "time": "2016-12-22 00:00:00"
            }
        },
        "ResultData": {
            "properties": {
                "id": {
                    "description": "Result Id",
                    "type": "integer",
                    "format": "int32"
                },
                "result": {
                    "description": "Result result",
                    "type": "int32"
                },
                "user_id": {
                    "description": "Result user associated",
                    "type": "int32"
                },
                "time": {
                    "description": "Result time",
                    "type": "datetime"
                }
            },
            "example": {
                "id": 1508,
                "result": 100,
                "user_id": 1,
                "time": "2016-12-22 00:00:00"
            }
        },
        "ResultsArray": {
            "properties": {
                "results": {
                    "description": "Results array",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Result"
                    }
                }
            }
        },
        "User": {
            "required": [
                "id",
                "username",
                "email"
            ],
            "properties": {
                "id": {
                    "description": "User Id",
                    "type": "integer",
                    "format": "int32"
                },
                "username": {
                    "description": "User name",
                    "type": "string"
                },
                "email": {
                    "description": "User email",
                    "type": "string"
                },
                "token": {
                    "description": "API access token",
                    "type": "string"
                },
                "enabled": {
                    "description": "Denotes if user is enabled",
                    "type": "boolean"
                }
            },
            "example": {
                "id": 1508,
                "username": "User name",
                "email": "User email",
                "enabled": true,
                "token": "$2$6a7f5b9e15f9c4a51495"
            }
        },
        "UserData": {
            "properties": {
                "username": {
                    "description": "User name",
                    "type": "string"
                },
                "email": {
                    "description": "User email",
                    "type": "string"
                },
                "password": {
                    "description": "User password",
                    "type": "string",
                    "format": "password"
                },
                "enabled": {
                    "description": "Denotes if user is enabled",
                    "type": "boolean"
                },
                "token": {
                    "description": "User token",
                    "type": "string"
                }
            },
            "example": {
                "username": "User_name",
                "email": "User_email@example.com",
                "password": "User_password",
                "enabled": true,
                "token": "$2$6a7f5b9e15f9c4a51495"
            }
        },
        "UsersArray": {
            "properties": {
                "users": {
                    "description": "Users array",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/User"
                    }
                }
            }
        },
        "Message": {
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "description": "Response code",
                    "type": "integer",
                    "format": "int32"
                },
                "message": {
                    "description": "Response message",
                    "type": "string"
                }
            },
            "example": {
                "code": "HTTP code",
                "message": "Response Message"
            }
        }
    },
    "parameters": {
        "resultId": {
            "name": "resultId",
            "in": "path",
            "description": "ID of result to fetch",
            "required": true,
            "type": "integer",
            "format": "int32"
        },
        "userId": {
            "name": "userId",
            "in": "path",
            "description": "ID of user to fetch",
            "required": true,
            "type": "integer",
            "format": "int32"
        }
    }
}